### PR TITLE
Updating to Laravel 5.1

### PR DESCRIPTION
**Pull request by PSmolic**
Updating to Laravel 5.1 LTS

This is still work in progress but I wanted to get your input. What do you think? Any suggestion what i might have missed?

I have working version of this branch here: http://l52.test.psmolic.com/

### CODE REVIEW

**Comment by stojankukrika** [comment]
well TNX for your work but I just pushed changes to laravel 5.1. Sorry I just see that you create a pull request :(

**Comment by PSmolic** [comment]
No problem , thank you for updating.

Part of my PR was some changes regarding .gitignore. When I run all commands to setup site i get something like this:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        config/local/
        public/appfiles/photoalbum/0babbe8d096396fcc02c211057377fe4.jpg
        public/appfiles/photoalbum/3c8da78dd33b330c130e1b185584592d.jpg
        public/appfiles/photoalbum/8fe438af7dbd4fff6910aa19df999200.jpg
        public/appfiles/photoalbum/ab6e505765bf9382dcd0bd0daa54fd2e.jpg
        public/appfiles/photoalbum/d9f85ce2a60919276fd90eea07a203b2.jpg
        public/appfiles/photoalbum/thumbs/0babbe8d096396fcc02c211057377fe4.jpg
        public/appfiles/photoalbum/thumbs/3c8da78dd33b330c130e1b185584592d.jpg
        public/appfiles/photoalbum/thumbs/8fe438af7dbd4fff6910aa19df999200.jpg
        public/appfiles/photoalbum/thumbs/ab6e505765bf9382dcd0bd0daa54fd2e.jpg
        public/appfiles/photoalbum/thumbs/d9f85ce2a60919276fd90eea07a203b2.jpg
        public/appfiles/videoalbum/27970bd755fdded55cdde8cadcf8bef0.jpg
        public/appfiles/videoalbum/2cb0c40f1755348107e7346b8d7dc853.jpg
        public/appfiles/videoalbum/6887d3f4fc142b70595accec276ce250.jpg
        public/appfiles/videoalbum/965f7f33ac6628d3d992be1f38416930.jpg
        public/appfiles/videoalbum/b02ff6c376e2099d3af8ab5e4432ba5b.jpg
        public/appfiles/videoalbum/thumbs/27970bd755fdded55cdde8cadcf8bef0.jpg
        public/appfiles/videoalbum/thumbs/2cb0c40f1755348107e7346b8d7dc853.jpg
        public/appfiles/videoalbum/thumbs/6887d3f4fc142b70595accec276ce250.jpg
        public/appfiles/videoalbum/thumbs/965f7f33ac6628d3d992be1f38416930.jpg
        public/appfiles/videoalbum/thumbs/b02ff6c376e2099d3af8ab5e4432ba5b.jpg
        public/build/css/
        public/build/js/
        storage/debugbar/
```
in my opinion all of this should be ignored since it is stuff that gets built with gulp or db seed. This makes it harder to continue to work on code..

If I make PR that ignores all of this without affecting functionality would you consider it?

**Comment by stojankukrika** [comment]
something like now it's look like?

**Comment by PSmolic** [comment]
works for me, Thanks! :)

**Comment by stojankukrika** [comment]
You're welcome ;)

**Pull request closed without merging**
